= Übung 05
:author: Florian Weingartshofer
:email: <S1910307103@students.fh-hagenberg.at>
:reproducible:
:experimental:
:listing-caption: Listing
:source-highlighter: rouge
:imgdir: ./img
:imagesoutdir: ./out
:stem:
:toc:
:numbered:

== Spannbaum Prim

=== a)
Kosten sind: latexmath:[$2 + 1 + 1 + 2 + 5 + 4 + 3 + 1 = 19$]

[graphviz]
----
strict graph "" {
	b -- a	[label=2];
	b -- c	[label=1];
	a -- d	[label=1];
	d -- e	[label=2];
	d -- g	[label=5];
	e -- f	[label=4];
	f -- h	[label=3];
	f -- i	[label=1];
}
----

== Spannbaum Kruskal

Kosten sind: latexmath:[$2 + 1 + 1 + 2 + 5 + 4 + 3 + 1 = 19$]

Die Kosten sind bei Prim und Kruskal gleich, allerdings unterscheiden sich die Spannbäume.

[graphviz]
----
strict graph "" {
	a -- b	[label=2];
	a -- d	[label=1];
	b -- c	[label=1];
	b -- e	[label=2];
	d -- g	[label=5];
	e -- f	[label=4];
	f -- h	[label=3];
	f -- i	[label=1];
}
----

<<<
== Minimale Spannbäume
=== a)
Kosten: latexmath:[$2 + 2 + 4 + 4 + 1 + 3 + 1 + 3 = 20$]

[graphviz]
----
include::all_spanning_trees/0.dot[]
----

[graphviz]
----
include::all_spanning_trees/1.dot[]
----

[graphviz]
----
include::all_spanning_trees/2.dot[]
----

[graphviz]
----
include::all_spanning_trees/3.dot[]
----

[graphviz]
----
include::all_spanning_trees/4.dot[]
----

=== b)
Man ersetzt im Graphen `G` alle Gewichte der Kanten durch ein Zahlenpaar,
die erste Zahl ist das eigentliche Gewicht,
als zweite Zahl vergibt man `0`, falls die Kante nicht in `T` vorkommt, ansonst `1`.
Diese Paare können miteinander verglichen oder addiert werden.

Danach wieder mit einem MST Algorithmus wieder einen MST suchen,
falls es noch einen MST gibt, hat dieser so wenig Kanten gemeinsam mit `T` wie möglich.

== Die MST Heuristik für das TSP
[graphviz]
----
strict graph "" {
	Wien -- Steyr	[label=166];
	Linz -- Hagenberg	[label=23];
	Hagenberg -- Steyr	[label=43.6];
	Graz -- Steyr	[label=191];
	Salzburg -- Wels	[label=108];
	Steyr -- Wels	[label=45.2];
}
----

== Minimale Spannbäume in gerichteten Graphen
Prim geht davon aus, dass alle Knoten von allen Knoten aus erreichbar sind.
Dies ist bei einem gerichtetem Graphen nicht der Fall, daher funktioniert Prim nicht.

Kruskal überprüft bei jedem Schritt, ob die Kanten einen Kreis bei dem momentanen Spannbaum bilden.
Dies funktioniert bei einem ungerichteten Graphen, allerdings gibt es Fälle bei gerichteten Graphen, die für
Kruskal wie ein Kreis ausschauen, es allerdings nicht sind.

.Beispiel Directed Graph Kruskal
[graphviz]
----
digraph "" {
    layout=circo
    1 -> 2
    3 -> 1
    3 -> 2
}
----

